ciphertext = """
C UYGHARMZ IUWMPRWIR GAIR YVRMP
MBHMZWMPUM C VMMXWPE YV PYR VCZ
ZMGYQMD VZYG CXCZG YP CPCXKTWPE CPD MBHXYZM
RNM VXYYD YV CDQCPUMD OPYSXMDEM SNWUN MCUN
KMCZ LZWPEI SWRN WR
"""

for i in range(26):
    print(chr(i + 65), ':', ciphertext.count(chr(i + 65)), end=', ')
